### ISSUE TITLE
Unhandled Rejection (WalletNotConnectedError): 

### ISSUE THREAD

**Issue by narodain** [ajobi-uhc/testSolanaGameNft#1]
When i press mint nft its showing this error : 

(anonymous function)
src/components/CreateNFT.js:33
  30 |          console.log('SIGNATURE', publicKey)
  31 | 
  32 | 
> 33 |      if (!publicKey) throw new WalletNotConnectedError();
     | ^  34 | 
  35 |     	// Create Mint account keypair
  36 | const mintAccount = web3.Keypair.generate();

**Comment by ajobi-uhc** [comment]
Hey I recommend you dont use this repository for minting NFT's on Solana. I would go to https://hackmd.io/@levicook/HJcDneEWF for a detailed guide on how to do that. Sorry for the issues
